import os
import base64
import re

profile_dir = "/Users/muaamal_rafid/Library/Developer/Xcode/UserData/Provisioning Profiles"
profile_path = os.path.join(profile_dir, "ec5b5d86-fb3a-48bb-8520-b05fd08adda9.mobileprovision")

# Ensure the directory exists
os.makedirs(profile_dir, exist_ok=True)

# Raw base64 from logs
base64_raw = (
    "MIINTAYJKoZIhvcNAQcCoIINPTCCDTkCAQExDTALBglghkgBZQMEAgEwggMLBgkqhkiG9w0BBwGgggL8BIIC"
    "+DGCAvQwDAwHVmVyc2lvbgIBATAPDApUaW1lVG9MaXZlAgEHMBMMDklzWGNvZGVNYW5hZ2VkAQH/MBMMDkxv"
    "Y2FsUHJvdmlzaW9uAQH/MBkMCFRlYW1OYW1lDA1NdWFhbWFsIFJhZmlkMB0MDENyZWF0aW9uRGF0ZRcNMjYw"
    "NTIzMTE0MjIzWjAeDA5UZWFtSWRlbnRpZmllcjAMDApaNkxaU1dLODlEMB8MDkV4cGlyYXRpb25EYXRlFw0y"
    "NjA1MzAxMTQyMjNaMCAMCUFwcElETmFtZQwTWEMgY29tIGR1ZGVzIHN1bnVubzAhDAhQbGF0Zm9ybTAVDANp"
    "T1MMBHhyT1MMCHZpc2lvbk9TMCIMF1Byb2ZpbGVEaXN0cmlidXRpb25UeXBlDAdMSU1JVEVEMCsMG0FwcGxp"
    "Y2F0aW9uSWRlbnRpZmllclByZWZpeDAMDApaNkxaU1dLODlEMCwMBFVVSUQMJGVjNWI1ZDg2LWZiM2EtNDhi"
    "Yi04NTIwLWIwNWZkMDhhZGRhOTAxDBJQcm92aXNpb25lZERldmljZXMwGwwZMDAwMDgxNDAtMDAwMTM5MEUy"
    "UkMyODAxQzA3DAROYW1lDC9pT1MgVGVhbSBQcm92aXNpb25pbmcgUHJvZmlsZTogY29tLmR1ZGVzLnN1bnVu"
    "bzA7DBVEZXZlbG9wZXJDZXJ0aWZpY2F0ZXMwIgQgpOGTcYfiQ/UDzE7vUBzZY8bvgD/AotJejplh3A7bbWk"
    "wgcAMDEVudGl0bGVtZW50c3CBrwIBAbCBqTA1DBZhcHBsaWNhdGlvbi1pZGVudGlmaWVyDBtaNkxaU1dLODlE"
    "LmNvbS5kdWRlcy5zdW51bm8wMQwjY29tLmFwcGxlLmRldmVsb3Blci50ZWFtLWlkZW50aWZpZXIMClo2TFpT"
    "V0s4OUQwEwwOZ2V0LXRhc2stYWxsb3cBAf8wKAwWa2V5Y2hhaW4tYWNjZXNzLWdyb3VwczAODAxaNkxaU1dL"
    "ODlELiqgggg9MIICQzCCAcmgAwIBAgIILcX8iNLFS5UwCgYIKoZIzj0EAwMwZzEbMBkGA1UEAwwSQXBwbGUg"
    "Um9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwK"
    "QXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwHhcNMTQwNDMwMTgxOTA2WhcNMzkwNDMwMTgxOTA2WjBnMRswGQYD"
    "VRQQDDBJBcHBsZSBSb290IENBIC0gRzMxJjAkBgNVBAsMHUFwcGxlIENlكرتيفيكاتيون Authhthortiy"
    "MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzB2MBAGByqGSM49AgEGBSuBBAAiA2IABJjpLz1A"
    "cqTtkyJygRMc3RCV8cWjTnHcFBbZDuWmBSp3ZHtfTjjTuxxEtX/1H7YyYl3J6YRbTzBPEVoA/VhYDKX1DyxN"
    "B0cTddqXl5dvMVztK517IDvYuVTZXpmkOlEKMaNCMEAwHQYDVR0OBBYEFLuw3qFYM4iapIqZ3r6966/ayySr"
    "MA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMDA2gAMGUCMQCD6cHEFl4aXTQY"
    "2e3v9GwOAEZLuN+yRhHFD/3meoyhpmvOwgPUnPWTxnS4at+qIxUCMG1mihDK1A3UT82NQz60imOlM27jbdoX"
    "t2QfyFMm+YhidDkLF1vLUagM6BgD56KyKDCCAuYwggJtoAMCAQICCDMN7vi/TGguMAoGCCqGSM49BAMDMGcx"
    "GzAZBgNVBAMMEkFwcGxlIFJvb3QgQ0EgLSBHMzEmMCQGA1UECwwdQXBwbGUgY2VydGlmaWNhdGlvbiBBdXRo"
    "b3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTMB4XDTE3MDIyMjIyMjMyMloXDTMyMDIx"
    "ODAwMDAwMFowcjEmMCQGA1UEAwwdQXBwbGUgU3lzdGVtIEludGVncmF0aW9uIENBIDQxJjAkBgNVBAsMHUFw"
    "cGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzBZ"
    "MBMGByqGSM49AgEGCCqGSM49AwEHA0IABAZrpFZvfZ8n0c42jpIbVs1UNmRKyZRomfrJIH7i9VgP3OJq6xlH"
    "Ly7vO6QBtAETRHxaJq2gnCkliuXmBm9PfFqjgfcwgfQwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBS7"
    "sN6hWDOImqSKmd6+veuv2sskqzBGBggrBgEFBQcBAQQ6MDgwNgYIKwYBBQUHMAGGKmh0dHA6Ly9vY3NwLmFw"
    "cGxlLmNvbS9vY3NwMDMtYXBwbGVyb290Y2FnMzA3BgNVHR8EMDAuMCygKqAohiZodHRwOi8vY3JsLmFwcGxl"
    "LmNvbS9hcHBsZXJvb3RjYWczLmNybDAdBgNVHQ4EFgQUeke6OIoVJEgiRs2+jxokezQDKmkwDgYDVR0PAQH/"
    "BAQDAgEGMBAGCiqGSIb3Y2QGAhEEAgUAMAoGCCqGSM49BAMDA2cAMGQCMBUMqY7Gr5Zpa6ef3VzUA1lsrlLU"
    "YMaLduC3xaLxCXzgmuNrseN8McQneqeOif2rdwIwYTMg8Sn/+YcyrinIZD12e1Gk0gIvdr5gIpHx1Tp13LTi"
    "xiqW/sYJ3EpP1STw/MqyMIIDCDCCAq2gAwIBAgIIdAw+OeWSqmAwCgYIKoZIzj0EAwIwcjEmMCQGA1UEAwwd"
    "QXBwbGUgU3lzdGVtIEludGVncmF0aW9uIENBIDQxJjAkBgNVBAsMHUFwcGxlIENlcnRpZmljYXRpb24gQXV0"
    "aG9yaXR5MRMwEQYDVQQKDApBcHBsZSBJbmMuMQswCQYDVQQGEwJVUzAeFw0yNjAxMjExOTI3MjBaFw0zMDAy"
    "MTkxOTI3MTlaME4xKjAoBgNVBAMMIVdXRFIgUHJvdmlzaW9uaW5nIFByb2ZpbGUgU2lnbmluZzETMBEGA1UE"
    "CgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASQCm+Jz9OBgDBU"
    "tbs6pwuprym2EdFvk+2+80naeXHuap2bh8FR/iTyDXjQNbtKIWOOBNG/prqOr5v40IQOfVE4o4IBTzCCAUsw"
    "DAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBR6R7o4ihUkSCJGzb6PGiR7NAMqaTBBBggrBgEFBQcBAQQ1MDMw"
    "MQYIKwYBBQUHMAGGJWh0dHA6Ly9vY3NwLmFwcGxlLmNvbS9vY3NwMDMtYXNpY2E0MDMwgZYGA1UdIASBjjCB"
    "izCBiAYJKoZIhvdjZAUBMHsweQYIKwYBBQUHAgIwbQxrVGhpcyBjZXJ0aWZpY2F0ZSBpcyB0byBiZSB1c2Vk"
    "IGV4Y2x1c2l2ZWx5IGZvciBmdW5jdGlvbnMgaW50ZXJuYWwgdG8gQXBwbGUgUHJvZHVjdHMgYW5kL29yIEFw"
    "cGxlIHByb2Nlc3Nlcy4wHQYDVR0OBBYEFOOR4Yl0AWakh+7/s1SL3TFLxV/QMA4GA1UdDwEB/wQEAwIHgDAP"
    "BgkqhkiG92NkDBMEAgUAMAoGCCqGSM49BAMCA0kAMEYCIQCKLAn4nkkRNCfreuBCB+NhMn/yhRqPnFAq2F2B"
    "3B0sVQIhAOFVnbz6f3aTic7DM6DDDyk69ZzwkC/ZX094Qnj1MdzUMYIB0zCCAc8CAQEwfjByMSYwJAYDVQQD"
    "DB1BcHBsZSBTeXN0ZW0gSW50ZWdyYXRpb24gQ0EgNDEmMCQGA1UECwwdQXBwbGUgQ2VydGlmaWNhdGlvbiBB"
    "dXRob3JpdHkxEzARBgNVBAoMCkFwcGxlIEluYy4xCzAJBgNVBAYTAlVTAgh0DD455ZKqYDALBglghkgBZQME"
    "AgGggecwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjYwNTIzMTE0MjIzWjAo"
    "BgkqhkiG9w0BCTQxGzAZMAsGCWCGSAFlAwQCAaEKBggqhkjOPQQDAjAvBgkqhkiG9w0BCQQxIgQgApTab158"
    "4SsWpVDvXB3XiQ/Nxag/ONOv7gHgTzBmYAEwUgYJKoZIhvcNAQkPMUUwQzAKBggqhkiG9w0DBzAOBggqhkiG"
    "9w0DAgICAIAwDQYIKoZIhvcNAwICAUAwBwYFKw4DAgcwDQYIKoZIhvcNAwICASgwCgYIKoZIzj0EAwIERzBF"
    "AiAULFZwhGuGvffRz1DouOMDjR84lxG619eyVSvfx9Q9UwIhAIgMP2AmS497yE6PY0qHV0reCtaSVKYEu4nd"
    "3R19KBjc="
)

# Clean up non-base64 characters
cleaned = re.sub(r'[^A-Za-z0-9+/=]', '', base64_raw)

# Fix padding if needed
while len(cleaned) % 4 != 0:
    cleaned += '='

binary_data = base64.b64decode(cleaned)

with open(profile_path, "wb") as f:
    f.write(binary_data)

print(f"Successfully restored provisioning profile to: {profile_path}")
